name: Static analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Android Lint
        run: ./gradlew lintDebug
      - name: Detekt
        run: ./gradlew detekt